In [1]:
!pip install opendatasets

In [2]:
# import packages
import numpy as np
import pandas as pd
import opendatasets as OD

In [3]:
# download the dataset
OD.download("https://www.kaggle.com/datasets/arunrk7/surface-crack-detection")

Skipping, found downloaded files in "./surface-crack-detection" (use force=True to force download)


In [4]:
import os
import cv2

In [5]:
# first work on positive images
positive_image_path = "/content/surface-crack-detection/Positive"

In [6]:
# first convert image to number


In [7]:
# to connect to that perticular folder os lib is use
# here we have multiple images so useing loop function

In [8]:
for filename in os.listdir(positive_image_path):
  print(filename)

Streaming output truncated to the last 5000 lines.
07555.jpg
06925.jpg
11577_1.jpg
17836_1.jpg
12742_1.jpg
07197.jpg
17400_1.jpg
18090_1.jpg
15606_1.jpg
12611_1.jpg
01373.jpg
11199_1.jpg
11361_1.jpg
19284_1.jpg
11250_1.jpg
11890_1.jpg
12663_1.jpg
07549.jpg
15879_1.jpg
03131.jpg
19524.jpg
01684.jpg
14800_1.jpg
04549.jpg
00272.jpg
16506_1.jpg
12602_1.jpg
00203.jpg
01725.jpg
03453.jpg
08135.jpg
09218.jpg
04854.jpg
00718.jpg
14494_1.jpg
14967_1.jpg
19509.jpg
18105_1.jpg
08443.jpg
06854.jpg
19546.jpg
10919_1.jpg
10079_1.jpg
17669_1.jpg
07993.jpg
00503.jpg
05348.jpg
03664.jpg
18557_1.jpg
13615_1.jpg
03885.jpg
04092.jpg
13322_1.jpg
03951.jpg
03362.jpg
01315.jpg
14727_1.jpg
15458_1.jpg
07692.jpg
00879.jpg
15659_1.jpg
03266.jpg
12073_1.jpg
17090_1.jpg
16373_1.jpg
17123_1.jpg
06442.jpg
13563_1.jpg
12277_1.jpg
15122_1.jpg
10703_1.jpg
02497.jpg
04800.jpg
08072.jpg
17097_1.jpg
14297_1.jpg
04724.jpg
18444_1.jpg
11299_1.jpg
03866.jpg
13480_1.jpg
19885.jpg
12479_1.jpg
00542.jpg
11487_1.jpg
15059_1.jpg

In [9]:
# path of each and every image
for filename in os.listdir(positive_image_path):
  specific_img_path = os.path.join(positive_image_path, filename)
  print(specific_img_path)

Streaming output truncated to the last 5000 lines.
/content/surface-crack-detection/Positive/07555.jpg
/content/surface-crack-detection/Positive/06925.jpg
/content/surface-crack-detection/Positive/11577_1.jpg
/content/surface-crack-detection/Positive/17836_1.jpg
/content/surface-crack-detection/Positive/12742_1.jpg
/content/surface-crack-detection/Positive/07197.jpg
/content/surface-crack-detection/Positive/17400_1.jpg
/content/surface-crack-detection/Positive/18090_1.jpg
/content/surface-crack-detection/Positive/15606_1.jpg
/content/surface-crack-detection/Positive/12611_1.jpg
/content/surface-crack-detection/Positive/01373.jpg
/content/surface-crack-detection/Positive/11199_1.jpg
/content/surface-crack-detection/Positive/11361_1.jpg
/content/surface-crack-detection/Positive/19284_1.jpg
/content/surface-crack-detection/Positive/11250_1.jpg
/content/surface-crack-detection/Positive/11890_1.jpg
/content/surface-crack-detection/Positive/12663_1.jpg
/content/surface-crack-detection/Positi

In [10]:
# we have to read the specific image interms of number
for filename in os.listdir(positive_image_path):
  specific_img_path = os.path.join(positive_image_path, filename)
  img = cv2.imread(specific_img_path)
  print(img)

Streaming output truncated to the last 5000 lines.
  [164 167 171]
  [163 166 170]]]
[[[142 140 146]
  [141 139 145]
  [141 139 145]
  ...
  [139 140 144]
  [137 138 142]
  [136 137 141]]

 [[143 141 147]
  [142 140 146]
  [142 140 146]
  ...
  [142 143 147]
  [140 141 145]
  [138 139 143]]

 [[145 143 149]
  [143 141 147]
  [143 141 147]
  ...
  [141 142 146]
  [139 140 144]
  [136 137 141]]

 ...

 [[141 140 150]
  [148 147 157]
  [152 151 161]
  ...
  [136 135 145]
  [136 135 145]
  [136 135 145]]

 [[150 149 159]
  [156 155 165]
  [158 157 167]
  ...
  [134 133 143]
  [134 133 143]
  [134 133 143]]

 [[158 157 167]
  [162 161 171]
  [161 160 170]
  ...
  [132 131 141]
  [132 131 141]
  [132 131 141]]]
[[[177 189 199]
  [182 194 204]
  [182 194 204]
  ...
  [189 202 210]
  [188 201 209]
  [188 201 209]]

 [[175 187 197]
  [181 193 203]
  [181 193 203]
  ...
  [186 199 207]
  [186 199 207]
  [185 198 206]]

 [[174 186 196]
  [178 190 200]
  [179 191 201]
  ...
  [183 196 204]
  [183 

In [11]:
# each and every img with diff size
# DL not getting diff size img we have to resize the img
for filename in os.listdir(positive_image_path):
  specific_img_path = os.path.join(positive_image_path, filename)
  img = cv2.imread(specific_img_path)
  img = cv2.resize(img,(64,64))
  print(img.shape)

Streaming output truncated to the last 5000 lines.
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(64, 64, 3)
(

In [12]:
# color accepting in terms of RGB

In [13]:
# creating two lists
Numeric_image = []
labels = []

In [14]:
for filename in os.listdir(positive_image_path):
  specific_img_path = os.path.join(positive_image_path, filename)
  img = cv2.imread(specific_img_path)  #numeric form of image
  img = cv2.resize(img,(64,64))        #resize the image
  img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
  Numeric_image.append(img)
  labels.append(1)

In [15]:
Numeric_image

[array([[[198, 187, 169],
         [197, 186, 168],
         [197, 186, 168],
         ...,
         [184, 175, 158],
         [175, 166, 149],
         [168, 158, 146]],
 
        [[194, 183, 165],
         [197, 186, 168],
         [196, 184, 166],
         ...,
         [187, 178, 161],
         [185, 176, 160],
         [190, 180, 168]],
 
        [[197, 186, 168],
         [198, 187, 169],
         [192, 180, 163],
         ...,
         [201, 192, 175],
         [190, 181, 164],
         [175, 165, 153]],
 
        ...,
 
        [[192, 180, 164],
         [193, 181, 165],
         [192, 181, 164],
         ...,
         [179, 170, 153],
         [177, 168, 151],
         [164, 155, 138]],
 
        [[195, 184, 167],
         [182, 170, 154],
         [188, 176, 160],
         ...,
         [180, 170, 154],
         [178, 169, 152],
         [177, 168, 151]],
 
        [[177, 165, 149],
         [181, 169, 153],
         [183, 171, 155],
         ...,
         [173, 164, 147],
  

In [16]:
# negative image for same approch

In [17]:
negative_imgage_path = "/content/surface-crack-detection/Negative"
for filename in os.listdir(negative_imgage_path):
  specific_img_path = os.path.join(negative_imgage_path, filename)
  img = cv2.imread(specific_img_path)  #numeric form of image
  img = cv2.resize(img,(64,64))        #resize the image
  img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
  Numeric_image.append(img)
  labels.append(0)

In [18]:
Numeric_image  # positive img and neg img in terms of numeric terms

[array([[[198, 187, 169],
         [197, 186, 168],
         [197, 186, 168],
         ...,
         [184, 175, 158],
         [175, 166, 149],
         [168, 158, 146]],
 
        [[194, 183, 165],
         [197, 186, 168],
         [196, 184, 166],
         ...,
         [187, 178, 161],
         [185, 176, 160],
         [190, 180, 168]],
 
        [[197, 186, 168],
         [198, 187, 169],
         [192, 180, 163],
         ...,
         [201, 192, 175],
         [190, 181, 164],
         [175, 165, 153]],
 
        ...,
 
        [[192, 180, 164],
         [193, 181, 165],
         [192, 181, 164],
         ...,
         [179, 170, 153],
         [177, 168, 151],
         [164, 155, 138]],
 
        [[195, 184, 167],
         [182, 170, 154],
         [188, 176, 160],
         ...,
         [180, 170, 154],
         [178, 169, 152],
         [177, 168, 151]],
 
        [[177, 165, 149],
         [181, 169, 153],
         [183, 171, 155],
         ...,
         [173, 164, 147],
  

In [19]:
labels  # dependent var where 1 is positive and 0 is negative

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [20]:
type(Numeric_image)

list

In [21]:
type(labels)

list

In [22]:
Numeric_image = np.array(Numeric_image)
labels = np.array(labels)

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(Numeric_image, labels,random_state = 100, test_size = 0.2 )

In [25]:
X_train.shape  #33111 is number of image, here 64 rows, 64 col, 3D data

(32000, 64, 64, 3)

In [26]:
X_test.shape

(8000, 64, 64, 3)

In [27]:
first_image = X_train[1]

In [28]:
first_image

array([[[162, 159, 152],
        [160, 157, 150],
        [160, 158, 150],
        ...,
        [145, 141, 129],
        [142, 138, 126],
        [136, 132, 120]],

       [[165, 162, 155],
        [155, 152, 145],
        [151, 148, 141],
        ...,
        [144, 140, 128],
        [130, 126, 114],
        [129, 125, 113]],

       [[161, 158, 151],
        [145, 141, 134],
        [141, 138, 131],
        ...,
        [143, 139, 127],
        [136, 132, 120],
        [143, 139, 127]],

       ...,

       [[162, 158, 147],
        [167, 163, 152],
        [174, 170, 159],
        ...,
        [164, 158, 146],
        [161, 156, 145],
        [159, 155, 143]],

       [[160, 156, 145],
        [175, 171, 160],
        [175, 171, 160],
        ...,
        [169, 163, 151],
        [156, 152, 140],
        [161, 157, 145]],

       [[155, 150, 139],
        [169, 165, 154],
        [153, 149, 138],
        ...,
        [170, 166, 154],
        [166, 162, 150],
        [167, 163, 152]]

In [29]:
# normalise the data
first_image = first_image / 255
# 255 is optimal value to normalise our images
# each value between 0 and 1

In [30]:
first_image

array([[[0.63529412, 0.62352941, 0.59607843],
        [0.62745098, 0.61568627, 0.58823529],
        [0.62745098, 0.61960784, 0.58823529],
        ...,
        [0.56862745, 0.55294118, 0.50588235],
        [0.55686275, 0.54117647, 0.49411765],
        [0.53333333, 0.51764706, 0.47058824]],

       [[0.64705882, 0.63529412, 0.60784314],
        [0.60784314, 0.59607843, 0.56862745],
        [0.59215686, 0.58039216, 0.55294118],
        ...,
        [0.56470588, 0.54901961, 0.50196078],
        [0.50980392, 0.49411765, 0.44705882],
        [0.50588235, 0.49019608, 0.44313725]],

       [[0.63137255, 0.61960784, 0.59215686],
        [0.56862745, 0.55294118, 0.5254902 ],
        [0.55294118, 0.54117647, 0.51372549],
        ...,
        [0.56078431, 0.54509804, 0.49803922],
        [0.53333333, 0.51764706, 0.47058824],
        [0.56078431, 0.54509804, 0.49803922]],

       ...,

       [[0.63529412, 0.61960784, 0.57647059],
        [0.65490196, 0.63921569, 0.59607843],
        [0.68235294, 0

In [31]:
# normalise the data
X_train = X_train / 255
X_test = X_test / 255

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

In [33]:
# define the model
model = Sequential()  # brain without neuron

In [34]:
model.add(Conv2D(32,(3,3), activation = 'relu', input_shape = (64,64,3) ))  # 32 is kernling with dim 3 by 3

In [35]:
model.add(MaxPooling2D(2,2))

In [36]:
model.add(Conv2D(64,(3,3), activation = 'relu'))
model.add(MaxPooling2D(2,2))

In [37]:
model.add(Conv2D(64,(3,3),activation = 'relu'))

In [38]:
model.add(Flatten())

In [39]:
# create ANN
model.add(Dense(64, activation = 'relu'))

In [40]:
# o/p layer
model.add(Dense(1, activation = 'sigmoid'))

In [41]:
  # loss and optimiser
model.compile(optimizer = 'adam',loss = "binary_crossentropy", metrics =["accuracy"] )

In [42]:
# training the model
model.fit(X_train, y_train ,epochs = 10 , batch_size = 32, validation_data= (X_test, y_test))

Epoch 1/10
1000/1000 [==============================] - 13s 7ms/step - loss: 0.0961 - accuracy: 0.9711 - val_loss: 0.0471 - val_accuracy: 0.9868
Epoch 2/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0488 - accuracy: 0.9868 - val_loss: 0.0360 - val_accuracy: 0.9887
Epoch 3/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0340 - accuracy: 0.9898 - val_loss: 0.0299 - val_accuracy: 0.9912
Epoch 4/10
1000/1000 [==============================] - 7s 7ms/step - loss: 0.0259 - accuracy: 0.9922 - val_loss: 0.0282 - val_accuracy: 0.9909
Epoch 5/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0200 - accuracy: 0.9939 - val_loss: 0.0136 - val_accuracy: 0.9959
Epoch 6/10
1000/1000 [==============================] - 7s 7ms/step - loss: 0.0163 - accuracy: 0.9951 - val_loss: 0.0220 - val_accuracy: 0.9930
Epoch 7/10
1000/1000 [==============================] - 6s 6ms/step - loss: 0.0169 - accuracy: 0.9952 - val_loss: 0.0155 - val_accuracy

In [43]:
image_path = "/content/surface-crack-detection/Positive/00004.jpg"

In [44]:
img = cv2.imread(image_path)
img = cv2.resize(img,(64,64))
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

In [45]:
img.shape

(64, 64, 3)

In [46]:
img = np.expand_dims(img, axis = 0)

In [47]:
img.shape # only one image

(1, 64, 64, 3)

In [48]:
prediction = model.predict(img)
print(prediction)

1/1 [==============================] - 0s 226ms/step
[[1.]]


In [49]:
if prediction[0][0] >= 0.5:
  print("crack")
else:
  print("no crack")

crack
